### ISSUE TITLE
scss mixing and importing problems.

### ISSUE THREAD

**Issue by ltxhhz** [balmjs/balm-ui#115]
你好 @elf-mouse ，我想查看文档中“标签页”的中的一个效果
![image](https://user-images.githubusercontent.com/51697596/154036808-fffbd2a6-4e40-4509-a8ea-11b10aecb856.png)
但我在复制代码之后不能正常运行
![image](https://user-images.githubusercontent.com/51697596/154037296-8776d87d-7712-4361-9498-4897b05794d7.png)
<hr>
我的项目是用vite构建的，这些是相关代码和配置

![image](https://user-images.githubusercontent.com/51697596/154037886-52660dd0-620b-475b-ab9c-a694529a7761.png)

![image](https://user-images.githubusercontent.com/51697596/154038034-918f0d90-3587-4db0-aea0-f5a8ed32658e.png)

![image](https://user-images.githubusercontent.com/51697596/154038052-dde8f4df-7700-41ba-aa03-67e955e3b937.png)

![image](https://user-images.githubusercontent.com/51697596/154038112-45229b97-da24-4912-bbe6-e7f6bceb6fc9.png)

我对scss了解并不多，麻烦您看下应该怎么做

**Comment by elf-mouse** [comment]
因为高定制化的主题需要引用 material 内部混合来实现 或 自行重写样式

上面的例子需要引入以下代码：

```scss
@use '@material/tab/mixins' as tab-mixins;
@use '@material/tab-indicator/mixins' as tab-indicator-mixins;
@use '@material/ripple/mixins' as ripple-mixins;
```

**Comment by ltxhhz** [comment]
@elf-mouse 你好大佬，感谢回复，我按您说的引入了，但还是出错，搞了一天还是不知道问题所在：
这样引入，和运行结果
![image](https://user-images.githubusercontent.com/51697596/154530732-0678d226-0cf9-4eed-9dac-db303b44389f.png)
![image](https://user-images.githubusercontent.com/51697596/154531512-44ce6704-9f2c-42d6-8a10-2c2f6f7c10be.png)

我把我的环境做了个简单的[模板](https://github.com/ltxhhz/balm-ui-test)，如果可以麻烦您帮我看一下
我太菜了

**Comment by elf-mouse** [comment]
抱歉，文档代码片段上的样式代码是早期MDC的用法，我已经更新了最新的代码片段

请查看最新 [tabs 文档](https://material.balmjs.com/navigation/tabs)

或直接复制以下代码：

```scss
@use "@material/tab/mixins" as tab-mixins;
@use "@material/tab-indicator/mixins" as tab-indicator-mixins;
@use "@material/ripple/mixins" as ripple-mixins;
@use "@material/theme" as color;

.demo-tab {
  flex: 0 1 auto;
}

.custom-tab {
  @include tab-mixins.text-label-color(color.$blue-300);
  @include tab-mixins.icon-color(color.$orange-300);
  .custom-tab-indicator {
    @include tab-indicator-mixins.underline-color(color.$pink-a700);
    @include tab-indicator-mixins.underline-height(5px);
    @include tab-indicator-mixins.underline-top-corner-radius(5px);
  }
  .mdc-tab__ripple {
    @include ripple-mixins.states(color.$pink-100);
  }
  &.mdc-tab--active {
    @include tab-mixins.text-label-color(color.$blue-900);
    @include tab-mixins.icon-color(color.$orange-900);
  }
}
```

学习本来就是循序渐进的过程，没有菜肉之说

再次感谢你的支持和细心
